### ISSUE TITLE
Lab 1 Feedback

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-Fall2019/lab1-Ryanwhitt1#1]
@Ryanwhitt1 

On line 167 of the Rmd document you have

To display the saved file as shown in Figure `\@ref(fig:whatever)`, use the `include_graphics()` function from `knitr`.^[The material in Section \@ref(lab) is modified from the Chapter 2 lab of [_An introduction to Statistical Learning_](http://faculty.marshall.usc.edu/gareth-james/ISL/ISLR%20Seventh%20Printing.pdf).]....

this is the wrong footnote.  It should be

`^[Use the argument `dpi = 96` inside `include_graphics()`.] `

The rest looks great.

**Comment by Ryanwhitt1** [comment]
@alanarnholt Changes made.

**Comment by alanarnholt** [comment]
@Ryannwhitt1

There are some spacing issues on line 167 with the second footnote....look at your answer and then compare to the solution....should be something like ^[Use the argument `dpi = 96` inside `include_graphics()`.]....note the backticks around dpi = 96 and include_graphics().

**Comment by Ryanwhitt1** [comment]
@alanarnholt Changes made -- let me know of any other fixes that might need to be done. Thanks.
